// Code generated by goyacc -o querystring.y.go querystring.y. DO NOT EDIT.

//line querystring.y:2
package querystring

import __yyfmt__ "fmt"

//line querystring.y:2

//line querystring.y:5
type yySymType struct {
	yys int
	s   string
	n   int
	q   Condition
}

const tSTRING = 57346
const tPHRASE = 57347
const tNUMBER = 57348
const tAND = 57349
const tOR = 57350
const tNOT = 57351
const tTO = 57352
const tPLUS = 57353
const tMINUS = 57354
const tCOLON = 57355
const tLEFTBRACKET = 57356
const tRIGHTBRACKET = 57357
const tLEFTRANGE = 57358
const tRIGHTRANGE = 57359
const tGREATER = 57360
const tLESS = 57361
const tEQUAL = 57362

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"tSTRING",
	"tPHRASE",
	"tNUMBER",
	"tAND",
	"tOR",
	"tNOT",
	"tTO",
	"tPLUS",
	"tMINUS",
	"tCOLON",
	"tLEFTBRACKET",
	"tRIGHTBRACKET",
	"tLEFTRANGE",
	"tRIGHTRANGE",
	"tGREATER",
	"tLESS",
	"tEQUAL",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 83

var yyAct = [...]int8{
	27, 26, 28, 32, 43, 32, 58, 57, 25, 33,
	54, 33, 32, 31, 53, 29, 30, 8, 33, 42,
	40, 32, 34, 36, 16, 17, 37, 33, 32, 19,
	38, 41, 44, 46, 33, 39, 47, 56, 48, 20,
	49, 5, 35, 51, 21, 22, 12, 32, 13, 1,
	4, 11, 18, 33, 55, 12, 10, 13, 23, 24,
	11, 3, 6, 7, 0, 10, 52, 32, 50, 32,
	45, 32, 12, 33, 13, 33, 9, 33, 2, 0,
	0, 15, 14,
}

var yyPact = [...]int16{
	51, -1000, -1000, 51, 68, -1000, -1000, -1000, 17, -1000,
	42, 42, 26, -1000, -1000, -1000, 42, 42, -7, -1000,
	-3, 22, 6, -1000, -1000, -1000, -1000, -1000, -1000, 15,
	-1, 65, -1000, 27, -1000, 41, -1000, 41, -1000, 63,
	-1000, -1000, 61, -1000, 4, 0, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 41, 32, -10, -11, -1000, -1000,
}

var yyPgo = [...]int8{
	0, 0, 76, 78, 61, 41, 17, 50, 49,
}

var yyR1 = [...]int8{
	0, 8, 3, 3, 4, 4, 5, 5, 5, 6,
	6, 6, 7, 7, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 1, 1,
}

var yyR2 = [...]int8{
	0, 1, 2, 1, 2, 1, 1, 3, 3, 1,
	3, 2, 1, 1, 1, 1, 3, 3, 3, 4,
	5, 4, 5, 3, 4, 3, 4, 4, 5, 4,
	5, 7, 7, 1, 2,
}

var yyChk = [...]int16{
	-1000, -8, -3, -4, -7, -5, 11, 12, -6, -2,
	14, 9, 4, 6, -3, -2, 7, 8, -5, -6,
	13, 18, 19, -5, -5, 15, 4, -1, 5, 18,
	19, 16, 6, 12, -1, 20, -1, 20, -1, 20,
	5, -1, 20, 5, -1, 5, 6, -1, -1, -1,
	5, -1, 5, 10, 10, -1, 5, 17, 17,
}

var yyDef = [...]int8{
	0, -2, 1, 3, 0, 5, 12, 13, 6, 9,
	0, 0, 14, 15, 2, 4, 0, 0, 0, 11,
	0, 0, 0, 7, 8, 10, 16, 17, 18, 0,
	0, 0, 33, 0, 23, 0, 25, 0, 19, 0,
	27, 21, 0, 29, 0, 0, 34, 24, 26, 20,
	28, 22, 30, 0, 0, 0, 0, 31, 32,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line querystring.y:26
		{
			yylex.(*lexerWrapper).query = yyDollar[1].q
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line querystring.y:31
		{
			yyVAL.q = NewAndCondition(yyDollar[1].q, yyDollar[2].q)
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line querystring.y:35
		{
			yyVAL.q = yyDollar[1].q
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line querystring.y:40
		{
			switch yyDollar[1].n {
			case queryMustNot:
				yyVAL.q = NewNotCondition(yyDollar[2].q)
			default:
				yyVAL.q = yyDollar[2].q
			}
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line querystring.y:49
		{
			yyVAL.q = yyDollar[1].q
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line querystring.y:54
		{
			yyVAL.q = yyDollar[1].q
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line querystring.y:58
		{
			yyVAL.q = NewAndCondition(yyDollar[1].q, yyDollar[3].q)
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
//line querystring.y:62
		{
			yyVAL.q = NewOrCondition(yyDollar[1].q, yyDollar[3].q)
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line querystring.y:67
		{
			yyVAL.q = yyDollar[1].q
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line querystring.y:71
		{
			yyVAL.q = yyDollar[2].q
		}
	case 11:
		yyDollar = yyS[yypt-2 : yypt+1]
//line querystring.y:75
		{
			yyVAL.q = NewNotCondition(yyDollar[2].q)
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line querystring.y:80
		{
			yyVAL.n = queryMust
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line querystring.y:84
		{
			yyVAL.n = queryMustNot
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line querystring.y:89
		{
			var opts *Options = nil
			if cyylex, ok := yylex.(CustomizableLexer); ok {
				opts = cyylex.GetOptions()
			}
			yyVAL.q = mustNewStringCondition(yyDollar[1].s, opts)
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line querystring.y:97
		{
			yyVAL.q = NewMatchCondition(yyDollar[1].s)
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line querystring.y:101
		{
			var opts *Options = nil
			if cyylex, ok := yylex.(CustomizableLexer); ok {
				opts = cyylex.GetOptions()
			}
			q := mustNewStringCondition(yyDollar[3].s, opts)
			q.SetField(yyDollar[1].s)
			yyVAL.q = q
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line querystring.y:111
		{
			val := yyDollar[3].s
			q := MustNewNumberRangeCondition(&val, &val, true, true)
			q.SetField(yyDollar[1].s)
			yyVAL.q = q
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line querystring.y:118
		{
			var opts *Options = nil
			if cyylex, ok := yylex.(CustomizableLexer); ok {
				opts = cyylex.GetOptions()
			}
			q := mustNewStringCondition(yyDollar[3].s, opts)
			q.SetField(yyDollar[1].s)
			yyVAL.q = q
		}
	case 19:
		yyDollar = yyS[yypt-4 : yypt+1]
//line querystring.y:128
		{
			val := yyDollar[4].s
			q := MustNewNumberRangeCondition(&val, nil, false, false)
			q.SetField(yyDollar[1].s)
			yyVAL.q = q
		}
	case 20:
		yyDollar = yyS[yypt-5 : yypt+1]
//line querystring.y:135
		{
			val := yyDollar[5].s
			q := MustNewNumberRangeCondition(&val, nil, true, false)
			q.SetField(yyDollar[1].s)
			yyVAL.q = q
		}
	case 21:
		yyDollar = yyS[yypt-4 : yypt+1]
//line querystring.y:142
		{
			val := yyDollar[4].s
			q := MustNewNumberRangeCondition(nil, &val, false, false)
			q.SetField(yyDollar[1].s)
			yyVAL.q = q
		}
	case 22:
		yyDollar = yyS[yypt-5 : yypt+1]
//line querystring.y:149
		{
			val := yyDollar[5].s
			q := MustNewNumberRangeCondition(nil, &val, false, true)
			q.SetField(yyDollar[1].s)
			yyVAL.q = q
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line querystring.y:156
		{
			val := yyDollar[3].s
			q := MustNewNumberRangeCondition(&val, nil, false, false)
			q.SetField(yyDollar[1].s)
			yyVAL.q = q
		}
	case 24:
		yyDollar = yyS[yypt-4 : yypt+1]
//line querystring.y:163
		{
			val := yyDollar[4].s
			q := MustNewNumberRangeCondition(&val, nil, true, false)
			q.SetField(yyDollar[1].s)
			yyVAL.q = q
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line querystring.y:170
		{
			val := yyDollar[3].s
			q := MustNewNumberRangeCondition(nil, &val, false, false)
			q.SetField(yyDollar[1].s)
			yyVAL.q = q
		}
	case 26:
		yyDollar = yyS[yypt-4 : yypt+1]
//line querystring.y:177
		{
			val := yyDollar[4].s
			q := MustNewNumberRangeCondition(nil, &val, true, false)
			q.SetField(yyDollar[1].s)
			yyVAL.q = q
		}
	case 27:
		yyDollar = yyS[yypt-4 : yypt+1]
//line querystring.y:184
		{
			phrase := yyDollar[4].s
			q := NewTimeRangeCondition(&phrase, nil, false, false)
			q.SetField(yyDollar[1].s)
			yyVAL.q = q
		}
	case 28:
		yyDollar = yyS[yypt-5 : yypt+1]
//line querystring.y:191
		{
			phrase := yyDollar[5].s
			q := NewTimeRangeCondition(&phrase, nil, true, false)
			q.SetField(yyDollar[1].s)
			yyVAL.q = q
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
//line querystring.y:198
		{
			phrase := yyDollar[4].s
			q := NewTimeRangeCondition(nil, &phrase, false, false)
			q.SetField(yyDollar[1].s)
			yyVAL.q = q
		}
	case 30:
		yyDollar = yyS[yypt-5 : yypt+1]
//line querystring.y:205
		{
			phrase := yyDollar[5].s
			q := NewTimeRangeCondition(nil, &phrase, false, true)
			q.SetField(yyDollar[1].s)
			yyVAL.q = q
		}
	case 31:
		yyDollar = yyS[yypt-7 : yypt+1]
//line querystring.y:212
		{
			min := yyDollar[4].s
			max := yyDollar[6].s
			q := MustNewNumberRangeCondition(&min, &max, true, true)
			q.SetField(yyDollar[1].s)
			yyVAL.q = q
		}
	case 32:
		yyDollar = yyS[yypt-7 : yypt+1]
//line querystring.y:220
		{
			min := yyDollar[4].s
			max := yyDollar[6].s
			q := NewTimeRangeCondition(&min, &max, true, true)
			q.SetField(yyDollar[1].s)
			yyVAL.q = q
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line querystring.y:229
		{
			yyVAL.s = yyDollar[1].s
		}
	case 34:
		yyDollar = yyS[yypt-2 : yypt+1]
//line querystring.y:233
		{
			yyVAL.s = "-" + yyDollar[2].s
		}
	}
	goto yystack /* stack new state and value */
}
